name: R Analysis with Docker

on: [push, pull_request]

jobs:
  run_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        # Build the Docker image based on Dockerfile and docker-compose.yml
        docker compose build

    - name: Start Docker container
      run: |
        # Start the container in detached mode
        docker compose up -d

    - name: Install R dependencies (renv restore)
      run: |
        docker exec rstudio_container Rscript -e "renv::restore()"

    - name: Run analysis script
      run: |
        docker exec rstudio_container Rscript scripts/analysis.R

    - name: Stop Docker container
      run: |
        # Stop the container after running the analysis
        docker compose down

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: analysis-results
        path: |
          results/output_plot.png
          results/output_data.csv
