name: Seurat basic analysis

on: [push, pull_request]

jobs:
  run_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        # Build the Docker image using the Dockerfile
        docker build -t rstudio_image .

    - name: Start Docker container
      run: |
        # Start the Docker container in detached mode
        docker run -d --name rstudio_container -v $(pwd)/data:/home/rstudio/data -v $(pwd)/scripts:/home/rstudio/scripts -v $(pwd)/results:/home/rstudio/results rstudio_image

    - name: Run Seurat analysis script
      run: |
        # Execute the R script inside the container
        docker exec rstudio_container Rscript scripts/seurat.R

    - name: Stop Docker container
      run: |
        # Stop and remove the container
        docker stop rstudio_container
        docker rm rstudio_container

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: seurat-results
        path: |
          results/feature_plot.png
          results/variable_features.png
